/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gohealth;

import com.gohealth.interview.Interview;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class Application {

    public static void main(String[] args) throws IOException {
        if(args.length==0) throw new IllegalArgumentException("filepath expected as first argument");

        System.out.println(new Interview(new FileReader(new File(args[0]))).histogram());
    }
}
